bind(
  name = "libssl",
  actual = "//third_party/boringssl:boringssl",
)

bind(
  name = "zlib",
  actual = "//third_party/zlib",
)


# Protobuf compiler binary
bind(
  name = "protoc",
  actual = "//third_party/protobuf/upstream:protoc"
)

# Library needed to build protobuf codegen plugin.
bind(
  name = "protobuf_compiler",
  actual = "//third_party/protobuf/upstream:protoc_lib",
)

# Library that C++ code generated by protobuf C compiler should depend
# on.
bind(
  name = "protobuf_clib",
  actual = "//third_party/protobuf/upstream:protobuf",
)

bind(
  name = "protobuf_java_lib",
  actual = "//third_party/protobuf:java_proto",
)

# GRPC codegen plugin
bind(
  name = "grpc_cpp_plugin",
  actual = "//third_party/grpc/upstream:grpc_cpp_plugin"
)

# GRPC C++ runtime library
bind(
  name = "grpc++",
  actual = "//third_party/grpc/upstream:grpc++"
)
