---
- name: Install strongswan
  apt: pkg={{item}} state=installed force=yes
  with_items:
    - strongswan
    - strongswan-plugin-xauth-noauth
    - strongswan-plugin-xauth-generic

- name: enable strongswan service
  service: name=strongswan enabled=yes

- name: copy strongswan.conf
  copy: src=strongswan/strongswan.conf dest=/etc/strongswan.conf owner=root group=root mode=0644
  notify: restart-strongswan

- name: copy root cert
  tags: cert
  copy: src=../spark/scripts/keystore/ca.cert.pem dest=/etc/ipsec.d/cacerts/ca.cert.pem owner=root group=root mode=0644

- name: copy strongswan service cert
  tags: cert
  copy: src=../spark/scripts/keystore/{{ ipsec_dns_name }}.cert.pem dest=/etc/ipsec.d/certs/{{ ipsec_dns_name }}.cert.pem owner=root group=root mode=0644

- name: copy strongswan service key
  tags: cert
  copy: src=../spark/scripts/keystore/{{ ipsec_dns_name }}.key.pem dest=/etc/ipsec.d/private/{{ ipsec_dns_name }}.key.pem owner=root group=root mode=0644

- name: fill ipsec.conf
  tags: config
  template: src=strongswan/ipsec.conf.j2 dest=/etc/ipsec.conf owner=root group=root mode=0664

- name: fill ipsec.secrets
  tags: config
  template: src=strongswan/ipsec.secrets.j2 dest=/etc/ipsec.secrets owner=root group=root mode=0600

- name: enable IP forward
  sysctl: name=net.ipv4.ip_forward value=1 state=present

- name: enable NAT
  template: src=strongswan/iptables-nat.sh.j2 dest=/etc/init.d/iptables-nat owner=root group=root mode=755
  notify: enables-iptables-nat

- name: enable iptables-nat service
  service: name=iptables-nat enabled=yes
